name: Docker Image CI

on: [push]
  #push:
  #  branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/alliander/docker-jenkins-jnlp-slave/$GITHUB_REF:$GITHUB_SHA
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/alliander/docker-jenkins-jnlp-slave/$GITHUB_REF:$GITHUB_SHA
